[package]
name = "dfunc"
version = "0.1.0"
edition = "2021"

[features]
default = []
enzyme = []

[dependencies]
num-traits = {version = "0.2.19", default-features = false}
diman = { path = "/home/jed/src/diman", default-features = false, features = ["f32", "si"] }
